### PR TITLE
just update gemfile

### PR DESCRIPTION
**Pull request by Mifrill**

### CODE REVIEW

**Comment by Mifrill** [comment]
locally passed

**Comment by zharikovpro** [comment]
In future use standard [Github workflow](https://guides.github.com/introduction/flow/) for collaboariation. Fork repo, push to your fork, then make PR.

**Comment by Mifrill** [comment]
I have no reason to do fork and support it separately

**Comment by zharikovpro** [comment]
There's no need to "support" fork. And the reason to make forks is collaboration, as [it's the standard way of collaborating on open source repositories on GitHub](https://help.github.com/articles/fork-a-repo/#propose-changes-to-someone-elses-project). That way any number of collaborators can propose changes, and main repo is protected and doesn't need to manage collaborators list specifically.

**Pull request closed without merging**
