### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by Mifrill**
Now the application can be deployed with one command

### CODE REVIEW

**Comment by zharikovpro** [comment]
This looks promising. However, it depends on `mifrill/railgun-browser`. To merge this into railgun itself, it would be great to have no external dependencies like that to the possible extent. Also I wonder why image has "browser" in it's name.

You can create a Wiki page in this repo with this instruction. It'll be OK even with external dependencies. No merge will be needed.

**Comment by Mifrill** [comment]
In this implementation, I packed the entire environment into one docker-image and put it on the docker hub ([url in readme](https://hub.docker.com/r/mifrill/railgun-browser/))

So I can change for using only the official docker assembly hub ubuntu and all other components If for you this are more comfortable, there will simply be a large Dockerfile, with all the settings

As for the wiki, I can not do this because I do not have the rights to create a wiki page

**Comment by zharikovpro** [comment]
Or, even better you can put docker image usage instructions right in the Docker Github and/or repository for the docker image. And I'll put a link to it in Readme.

**Comment by zharikovpro** [comment]
Added link in README.

**Pull request closed without merging**
