### PR TITLE
Issue 192

### PR DESCRIPTION
**Pull request by Mifrill**

### CODE REVIEW

**Comment by zharikovpro** [comment]
Will review and merge with minor changes probably on the weekend.

**Comment by zharikovpro** [comment]
AnyLogin has several drawbacks: 

1) works only for one model (some apps have several user models, like User and AdminUser)
2) works well only with short list of users, otherwise it's not handly to select user from large list or remember ID.

Better solution will be something like this:

Override [devise controller](https://stackoverflow.com/questions/10070845/rails3-devise-login-as-any-user-without-pass) to allow login without password (only by email) in development mode only.

**Comment by zharikovpro** [comment]
[Example code.](https://stackoverflow.com/questions/7888747/devise-custom-authentication-without-a-password)

**Comment by Mifrill** [comment]
In this application (Railgun) there are several user models?
    Since when are some applications and Railgun this one and the same?
    Since when do we solve mythical problems that do not exist now?
    What problem do you solve, paying attention to several user models - mythical or concrete?
In issue #192, it was indicated that it is necessary to consider the possibility of using several user models?

The solution in this PR clearly and with a minimum amount of code solves the assigned, specific task, in a specific project.

>[ Example code.](https://stackoverflow.com/questions/7888747/devise-custom-authentication-without-a-password)

The above code example was considered when searching for a solution before creating pr, and was excluded, because Did not solve the task since there is no example of code for the model, and when writing it, it turned out that this is significantly more code and is correspondingly more difficult to support than in this implementation

In the development mode, the base is mainly used, where there is no need create a large number of users.
And in case there is a need, you can change frontend of this gem and organize your own search, by email or any other parameter, but in a separate issue.

**Comment by Mifrill** [comment]
In comments on pr I do not see the reason for closing pr

**Comment by zharikovpro** [comment]
> In this application (Railgun) there are several user models?

In Railgun no. It's in two differrent apps, one of them is based on Railgun. Railgun purpose is to serve as a universal boilerplate for those projects, too.

> What problem do you solve, paying attention to several user models - mythical or concrete?

It's the real requirement in two apps. Also, UI of selecting user by ID is barely usable anyway. Emails are the way to go as they are easy to remember.

> In the development mode, the base is mainly used, where there is no need create a large number of users.

Regardless of number of users I do not want to somehow look up and then enter user id. That same way I can lookup password and then enter it - thus, no benefit. With passwordless login by email is the way to go. Refined issue #192 and added the requirement for entering email only for authentification.

> and organize your own search, by email or any other parameter, but in a separate issue.

There's no need to make any UI or organize search. Authentication by email only will work best. No UI, unobtrusive, works everywhere. It's not that hard to implement. Also, there will be no gem dependency.

> In comments on pr I do not see the reason for closing pr

Reasons are [there](https://github.com/zharikovpro/railgun/pull/197#issuecomment-317255154), and also in this comment.

**Comment by Mifrill** [comment]
I understood the arguments
I has one question:

> That same way I can lookup password and then enter it

How? It's in encrypted form and we just can check it for validity the password but we can not be looked at.

**Comment by zharikovpro** [comment]
This part was posted by a mistake. I can't really look up password via console, only reset. Ultimately, I want neither look up nor reset. It's common to create several users for testing with easy to remember emails (like dev email, owner email, use case persona email, etc).

**Pull request closed without merging**
