### PR TITLE
Gemnasium update.

### PR DESCRIPTION
**Pull request by zharikovpro**

### CODE REVIEW

**Comment by Mifrill** [comment]
https://github.com/zharikovpro/railgun/pull/195/commits/4f34c79c0655bd509d94e536ba28b3eeb6079602

**Comment by zharikovpro** [comment]
This is not great in some case. I need either proof that this will be incorrect or proof that the change will be safe. It is a long story to remember.

**Comment by zharikovpro** [comment]
Will leave it here hanging for now as a reminder. Once it was a real issue.

**Comment by zharikovpro** [comment]
Ok, here's the decision. If it ever will be the pain again, will add specs for the edge case. A lot of Rails folks use rack-cors, so will rely on their implementation, specs, and fixes.

**Pull request merged**
